version: 2
updates:
  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # Maintain dependencies for numberneighbors.
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily

  # Maintain dependencies for web.
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: daily
