server:
  port: ${env.PORT:8080}

spring:
  datasource:
    username: ${env.POSTGRES_USER}
    password: ${env.POSTGRES_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: ${env.DDL_AUTO:update}

    properties:
      hibernate:
        default_schema: public
        jdbc:
          lob:
            # Fix Postgres JPA Error (Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented).
            non_contextual_creation: true
          batch_size: 50
        default_batch_fetch_size: 50
        dialect: org.hibernate.dialect.PostgreSQLDialect

client:
  uri: ${env.CLIENT_URI}
