spring:
  datasource:
    url: jdbc:postgresql://${env.POSTGRES_HOSTNAME}:${env.POSTGRES_PORT}/${env.POSTGRES_DB}?sslmode=disable

jwt:
  private:
    key: rsakey.pem
  public:
    key: rsapubkey.pem
