name: Continuous Deployment

on:
  push:
    branches: [main, feat/fly-io-deployment]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/kucera-lukas/number-neighbors:latest
  CACHE_IMAGE_NAME: ghcr.io/kucera-lukas/number-neighbors-paketo-cache-image:latest

jobs:
  build-and-push-image:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        os: [ubuntu-latest]
        pack: [7.37.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pack CLI
        uses: buildpacks/github-actions/setup-pack@v4.8.1

      # Caching Paketo Build, see https://stackoverflow.com/a/66598693/4964553
      #
      # BP_JVM_VERSION 17, because we use Java 17 inside our Maven build
      # but Paketo defaults to 11
      - name: Build app with pack CLI & publish to GitHub Container Registry
        env:
          PACK_VERSION: ${{ matrix.pack }}
        run: |
          pack build $IMAGE_NAME \
              --builder paketobuildpacks/builder:tiny \
              --buildpack paketo-buildpacks/java-native-image@$PACK_VERSION \
              --path . \
              --env "BP_JVM_VERSION=17" \
              --env "BP_NATIVE_IMAGE=true" \
              --cache-image $CACHE_IMAGE_NAME \
              --publish

  deploy:
    needs: build-and-push-image

    runs-on: ${{ matrix.os }}

    permissions:
      packages: read

    strategy:
      matrix:
        os: [ubuntu-latest]

    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy app to fly.io
        run: flyctl deploy --image $IMAGE_NAME
