name: Continuous Deployment

on:
  push:
    branches: [main, feat/aws-ec2-terraform]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/kucera-lukas/number-neighbors

jobs:
  build-and-push-image:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:sha-${{ github.sha }}

  deploy:
    needs: build-and-push-image

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: read

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Deploy to Amazon EC2 via SSH action
        uses: appleboy/ssh-action@v0.1.3
        env:
          DOCKER_REGISTRY: ${{ env.REGISTRY }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ github.sha }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSHKEY }}
          envs: DOCKER_REGISTRY,DOCKER_USERNAME,DOCKER_PASSWORD,SHA,IMAGE_NAME,PRIVATE_KEY,PUBLIC_KEY
          script_stop: true
          script: |
            export DOCKER_REGISTRY=$DOCKER_REGISTRY
            export DOCKER_USERNAME=$DOCKER_USERNAME
            export DOCKER_PASSWORD=$DOCKER_PASSWORD
            export SHA=$SHA
            export IMAGE_NAME=$IMAGE_NAME
            export PRIVATE_KEY=$PRIVATE_KEY
            export PUBLIC_KEY=$PUBLIC_KEY
            bash number-neighbors/deploy.sh
