name: Continuous Integration

on: [push]

jobs:
  build:
    name: JDK ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      # make sure that we can write SpotBugs report,
      # for example the Dependabot token is read-only by default.
      checks: write

    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [17]
        distribution: [temurin]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: maven

      - name: Build with Maven
        run: |
          mvn clean install spotbugs:spotbugs --batch-mode --update-snapshots --show-version -DskipTests=true

      - name: Push SpotBugs report
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: "**/spotbugsXml.xml"
