name: Continuous Integration

on: [push]

jobs:
  build:
    name: JDK ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [17]
        distribution: [temurin, adopt]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: maven

      - name: Build with Maven
        run: |
          mvn clean install spotbugs:check --batch-mode --update-snapshots --show-version -DskipTests=true

      - name: Push SpotBugs report
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: "**/spotbugsXml.xml"
