name: Continuous Integration

on: [push]

jobs:
  java:
    name: JDK ${{ matrix.java }}
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      # make sure that we can write SpotBugs report,
      # for example the Dependabot token is read-only by default.
      checks: write

    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [17]
        distribution: [temurin]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: maven

      - name: Build with Maven
        run: |
          mvn clean install --batch-mode --update-snapshots --show-version -DskipTests=true

  web:
    name: web
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    defaults:
      run:
        working-directory: web

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          cache-dependency-path: web/package-lock.json

      - name: Install packages
        run: npm ci

      - name: Prettier
        run: npm run fmt:check

      - name: ESLint
        run: npm run lint:fix
